export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
export const ADD_ITEM = 'ADD_ITEM';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CLEAR_CART = 'CLEAR_CART';

export const UPDATE_CART_IN_FIREBASE = 'UPDATE_CART_IN_FIREBASE';
export const SET_CART_FROM_FIREBASE = 'SET_CART_FROM_FIREBASE';
